name: MariaDB service example
on: push

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie


    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      maria-db:
        # Docker Hub image
        image: mariadb:latest
        # Provide the password for postgres
        env:
          MARIADB_ROOT_PASSWORD: 1234
          MARIADB_DATABASE: data_mysql
          MARIADB_USER: juba
          MARIADB_PASSWORD: 1234
        # Set health checks to wait until postgres has started
        options: >-
           --health-cmd "mysql -uroot -p'1234' --execute 'SHOW DATABASES;'"
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5
        #   --expose 5306 not needed because the app is on the same workflow
    steps:
      # - name: Git support longpaths
      #   run: git config --global core.longpaths true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file ./utilisateurs/pom.xml  

        env:
          # The hostname used to communicate with the mariadb service container
         
          LOGLEVEL: debug
          DB_HOST: maria_db
          DB_PORT: 3306
          DB_USER: juba
          DB_PASSWORD: 1234
          DB_DATABASE: data_mysql
